---
- hosts: all
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install NGINX Plus
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_type: plus
        nginx_version: "=32-1~focal"
        nginx_license:
          certificate: ~/nginx-repo.crt
          key: ~/nginx-repo.key
        nginx_remove_license: false

    - name: Install NGINX App Protect WAF/DoS
      ansible.builtin.include_role:
        name: nginx_app_protect
      vars:
        nginx_app_protect_version: "=32+5.48.0-1~focal"
        nginx_app_protect_waf_version: "=32+5.48.0-1~focal"
        nginx_app_protect_dos_version: "=32+4.4.1-1~focal"
        nginx_app_protect_waf_enable: true
        nginx_app_protect_dos_enable: true
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
        nginx_app_protect_setup_license: false
        nginx_app_protect_remove_license: false
