---
- hosts: all
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: CleanUp nginx.conf for Uninstall
      ansible.builtin.include_role:
        name: nginx_config
      vars:
        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          deployment_location: /etc/nginx/nginx.conf
          backup: true

    - name: Uniinstall NGINX Plus
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_type: plus
        nginx_setup: uninstall
        nginx_license:
          certificate: ~/nginx-repo.crt
          key: ~/nginx-repo.key
        nginx_remove_license: false
        nginx_start: false

    - name: Uninstall NGINX App Protect WAF/DoS
      ansible.builtin.include_role:
        name: nginx_app_protect
      vars:
        nginx_app_protect_waf_setup: uninstall
        nginx_app_protect_dos_setup: uninstall
        nginx_app_protect_setup_license: false
        nginx_app_protect_remove_license: false
        nginx_app_protect_start: false
